import { Dimensions, Platform } from 'react-native';
import { scaledStyleSheet } from '../../lib/scale';

const { width: SCREEN_WIDTH, height: SCREEN_HEIGHT } = Dimensions.get('window');

export const styles = scaledStyleSheet({
  container: {
    flex: 1,
  },
  gradient: {
    flex: 1,
    position: 'relative',
    overflow: 'hidden',
  },
  timelineBlob: {
    position: 'absolute',
    borderRadius: 1000,
  },
  header: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingHorizontal: 20,
    paddingTop: 65,
    paddingBottom: 20,
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.2)',
  },
  backButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  headerTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  // ═══════════════════════════════════════════════════════════════
  // Planning Submit/Cancel Buttons Styles
  // ═══════════════════════════════════════════════════════════════
  planningActionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 12,
  },
  planningSubmitButton: {
    position: 'absolute',
    top: 130,
    right: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(16, 185, 129, 0.3)',
    paddingHorizontal: 28,
    paddingVertical: 4,
    borderRadius: 24,
    gap: 8,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    minHeight: 38,
    minWidth: 100,
    elevation: 10000,
    zIndex: 10000,
    shadowColor: '#10B981',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  planningSubmitButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  planningCancelButton: {
    position: 'absolute',
    top: 130,
    left: 20,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(107, 114, 128, 0.3)',
    paddingHorizontal: 28,
    paddingVertical: 4,
    borderRadius: 24,
    gap: 8,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    minHeight: 38,
    minWidth: 100,
    elevation: 10000,
    zIndex: 10000,
    shadowColor: '#6B7280',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
  },
  planningCancelButtonText: {
    color: '#FFFFFF',
    fontSize: 17,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  // ═══════════════════════════════════════════════════════════════
  editButtonContainer: {
    position: 'absolute',
    top: '54%',
    left: '39%',
    transform: [{ translateX: -50 }],
    marginLeft: 0,
    marginTop: 0,
    paddingRight: 0,
    paddingBottom: 0,
    alignItems: 'center',
    alignSelf: 'center',
    zIndex: 9999,
    elevation: 9999,
  },
  editModeButton: {
    paddingHorizontal: 28,
    paddingVertical: 4,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    minHeight: 38,
    minWidth: 100,
    zIndex: 10000,
    elevation: 10000,
  },
  editModeButtonInactive: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  editModeButtonActive: {
    backgroundColor: '#60A5FA',
    borderColor: '#FFFFFF',
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 15,
  },
  editModeButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  editModeButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  viewButtonContainer: {
    position: 'absolute',
    top: '41%',
    left: '50%',
    marginRight: 0,
    marginTop: 0,
    paddingLeft: 0,
    paddingBottom: 0,
    alignItems: 'center',
    alignSelf: 'center',
    zIndex: 9999,
    elevation: 9999,
  },
  viewModeButton: {
    paddingHorizontal: 28,
    paddingVertical: 4,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 2,
    minHeight: 38,
    minWidth: 100,
    zIndex: 10000,
    elevation: 10000,
  },
  viewModeButtonInactive: {
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#3B82F6',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.4,
    shadowRadius: 6,
    elevation: 4,
  },
  viewModeButtonActive: {
    backgroundColor: '#60A5FA',
    borderColor: '#FFFFFF',
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 20,
    elevation: 15,
  },
  viewModeButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#FFFFFF',
    letterSpacing: 0.5,
  },
  viewModeButtonTextActive: {
    color: '#FFFFFF',
    fontWeight: '800',
  },
  toothGlowEffect: {
    shadowColor: '#60A5FA',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0.8,
    shadowRadius: 15,
    elevation: 8,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.7)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  toothDetailsModalContainer: {
    width: '95%',
    maxHeight: '85%',
    backgroundColor: '#1E293B',
    borderRadius: 20,
    overflow: 'hidden',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 20,
    elevation: 10,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 20,
    paddingVertical: 16,
    backgroundColor: '#334155',
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(96, 165, 250, 0.3)',
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  modalCloseButton: {
    padding: 4,
  },
  modalScrollView: {
    flex: 1,
  },
  modalSection: {
    padding: 16,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(255, 255, 255, 0.1)',
  },
  modalSectionTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#60A5FA',
    marginBottom: 12,
  },
  modalInfoCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(59, 130, 246, 0.1)',
    padding: 12,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.3)',
  },
  modalInfoText: {
    fontSize: 15,
    color: '#FFFFFF',
    fontWeight: '600',
  },
  surfacesContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 8,
  },
  surfaceChip: {
    backgroundColor: 'rgba(96, 165, 250, 0.2)',
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 16,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.4)',
  },
  surfaceChipText: {
    color: '#60A5FA',
    fontSize: 13,
    fontWeight: '600',
  },
  conditionsGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 12,
  },
  conditionItem: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.05)',
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
  },
  conditionLabel: {
    color: '#FFFFFF',
    fontSize: 13,
    fontWeight: '600',
  },
  noDataContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 60,
    gap: 12,
  },
  noDataText: {
    fontSize: 16,
    color: '#9CA3AF',
    textAlign: 'center',
  },
  noDataSubText: {
    fontSize: 14,
    color: '#6B7280',
    textAlign: 'center',
    marginTop: 8,
  },
  modalContentPadding: {
    padding: 16,
  },
  modalToothCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 16,
  },
  modalSectionSubtitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    marginBottom: 12,
  },
  modalSurfaceChip: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    gap: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.25)',
  },
  surfaceColorIndicator: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  surfaceChipLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  modalDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    marginVertical: 16,
  },
  additionalInfoSection: {
    gap: 12,
  },
  infoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  infoLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.8)',
    flex: 1,
  },
  infoValue: {
    fontSize: 15,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  instructionsCard: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    backgroundColor: 'rgba(96, 165, 250, 0.15)',
    padding: 14,
    borderRadius: 12,
    borderWidth: 1,
    borderColor: 'rgba(96, 165, 250, 0.3)',
  },
  instructionsText: {
    flex: 1,
    fontSize: 13,
    color: 'rgba(255, 255, 255, 0.9)',
    lineHeight: 18,
  },
  headerSpacer: {
    width: 44,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingVertical: 20,
    paddingHorizontal: 10,
    flexGrow: 1,
    justifyContent: 'flex-start',
  },
  crossContainer: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
    zIndex: 1000,
    elevation: 1000,
  },
  dividerCross: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  centerDivider: {
    position: 'absolute',
    width: '100%',
    height: '100%',
    alignItems: 'center',
    justifyContent: 'center',
  },
  oralHygieneContainer: {
    position: 'absolute',
    top: '50%',
    left: '50%',
    backgroundColor: 'rgba(254, 215, 170, 0.2)',
    paddingHorizontal: 16,
    paddingVertical: 4,
    borderRadius: 16,
    borderWidth: 1.5,
    borderColor: 'rgba(254, 215, 170, 0.5)',
    zIndex: 800,
    elevation: 800,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.1,
    shadowRadius: 12,
  },
  oralHygieneText: {
    color: '#92400E',
    fontSize: 16,
    fontWeight: '700',
    letterSpacing: 0.5,
    textAlign: 'center',
  },
  scalingButton: {
    paddingVertical: 18,
    paddingHorizontal: 20,
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(16, 185, 129, 0.5)',
    marginBottom: 16,
  },
  scalingButtonText: {
    color: '#059669',
    fontSize: 15,
    fontWeight: '700',
  },
  scalingRecordsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 12,
    padding: 12,
  },
  scalingRecordsTitle: {
    fontSize: 14,
    fontWeight: '600',
    color: '#92400E',
    marginBottom: 12,
  },
  scalingRecordItem: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    padding: 10,
    borderRadius: 8,
    marginBottom: 8,
  },
  scalingRecordIcon: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(251, 191, 36, 0.2)',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 10,
  },
  scalingRecordInfo: {
    flex: 1,
  },
  scalingRecordDoctor: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 2,
  },
  scalingRecordTime: {
    fontSize: 12,
    color: '#64748B',
  },
  deleteRecordButton: {
    padding: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(239, 68, 68, 0.1)',
  },
  // Tooth positions 1-8
  tooth8: {
    position: 'absolute',
    right: 45,
    top: '42%',
    width: 37,
    height: 47,
  },
  tooth7: {
    position: 'absolute',
    right: 45,
    top: '36%',
    width: 37,
    height: 47,
  },
  tooth6: {
    position: 'absolute',
    right: 45,
    top: '30%',
    width: 37,
    height: 47,
  },
  tooth5: {
    position: 'absolute',
    right: 55,
    top: '24%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-15deg' }],
  },
  tooth4: {
    position: 'absolute',
    right: 67,
    top: '18.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-20deg' }],
  },
  tooth3: {
    position: 'absolute',
    right: 90,
    top: '14%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-35deg' }],
  },
  tooth2: {
    position: 'absolute',
    right: 120,
    top: '10%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-60deg' }],
  },
  tooth1: {
    position: 'absolute',
    right: 160,
    top: '7.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-80deg' }],
  },
  // Tooth positions 9-16
  tooth9: {
    position: 'absolute',
    left: 45,
    top: '42%',
    width: 37,
    height: 47,
  },
  tooth10: {
    position: 'absolute',
    left: 45,
    top: '36%',
    width: 37,
    height: 47,
  },
  tooth11: {
    position: 'absolute',
    left: 45,
    top: '30%',
    width: 37,
    height: 47,
  },
  tooth12: {
    position: 'absolute',
    left: 55,
    top: '24%',
    width: 33,
    height: 42,
    transform: [{ rotate: '15deg' }],
  },
  tooth13: {
    position: 'absolute',
    left: 67,
    top: '18.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '20deg' }],
  },
  tooth14: {
    position: 'absolute',
    left: 90,
    top: '14%',
    width: 33,
    height: 42,
    transform: [{ rotate: '35deg' }],
  },
  tooth15: {
    position: 'absolute',
    left: 120,
    top: '10%',
    width: 33,
    height: 42,
    transform: [{ rotate: '60deg' }],
  },
  tooth16: {
    position: 'absolute',
    left: 160,
    top: '7.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '80deg' }],
  },
  // Tooth positions 17-24
  tooth17: {
    position: 'absolute',
    right: 160,
    bottom: '7.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '80deg' }],
  },
  tooth18: {
    position: 'absolute',
    right: 120,
    bottom: '10%',
    width: 33,
    height: 42,
    transform: [{ rotate: '60deg' }],
  },
  tooth19: {
    position: 'absolute',
    right: 90,
    bottom: '14%',
    width: 33,
    height: 42,
    transform: [{ rotate: '35deg' }],
  },
  tooth20: {
    position: 'absolute',
    right: 67,
    bottom: '18.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '20deg' }],
  },
  tooth21: {
    position: 'absolute',
    right: 55,
    bottom: '24%',
    width: 33,
    height: 42,
    transform: [{ rotate: '15deg' }],
  },
  tooth22: {
    position: 'absolute',
    right: 45,
    bottom: '30%',
    width: 37,
    height: 47,
  },
  tooth23: {
    position: 'absolute',
    right: 45,
    bottom: '36%',
    width: 37,
    height: 47,
  },
  tooth24: {
    position: 'absolute',
    right: 45,
    bottom: '42%',
    width: 37,
    height: 47,
  },
  // Tooth positions 25-32
  tooth25: {
    position: 'absolute',
    left: 45,
    bottom: '42%',
    width: 37,
    height: 47,
  },
  tooth26: {
    position: 'absolute',
    left: 45,
    bottom: '36%',
    width: 37,
    height: 47,
  },
  tooth27: {
    position: 'absolute',
    left: 45,
    bottom: '30%',
    width: 37,
    height: 47,
  },
  tooth28: {
    position: 'absolute',
    left: 55,
    bottom: '24%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-15deg' }],
  },
  tooth29: {
    position: 'absolute',
    left: 67,
    bottom: '18.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-20deg' }],
  },
  tooth30: {
    position: 'absolute',
    left: 90,
    bottom: '14%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-35deg' }],
  },
  tooth31: {
    position: 'absolute',
    left: 120,
    bottom: '10%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-60deg' }],
  },
  tooth32: {
    position: 'absolute',
    left: 160,
    bottom: '7.5%',
    width: 33,
    height: 42,
    transform: [{ rotate: '-80deg' }],
  },
  // Tooth Numbers 1-8
  toothNumber1: {
    position: 'absolute',
    right: 165,
    top: '5%',
    transform: [{ rotate: '-80deg' }],
  },
  toothNumber2: {
    position: 'absolute',
    right: 115,
    top: '8.5%',
    transform: [{ rotate: '-50deg' }],
  },
  toothNumber3: {
    position: 'absolute',
    right: 75,
    top: '12.5%',
    transform: [{ rotate: '-35deg' }],
  },
  toothNumber4: {
    position: 'absolute',
    right: 40,
    top: '19%',
    transform: [{ rotate: '-15deg' }],
  },
  toothNumber5: {
    position: 'absolute',
    right: 30,
    top: '23.5%',
    transform: [{ rotate: '-15deg' }],
  },
  toothNumber6: {
    position: 'absolute',
    right: 20,
    top: '31.5%',
  },
  toothNumber7: {
    position: 'absolute',
    right: 20,
    top: '37.5%',
  },
  toothNumber8: {
    position: 'absolute',
    right: 20,
    top: '43.5%',
  },
  // Tooth Numbers 9-16
  toothNumber9: {
    position: 'absolute',
    left: 165,
    top: '5%',
    transform: [{ rotate: '80deg' }],
  },
  toothNumber10: {
    position: 'absolute',
    left: 115,
    top: '8.5%',
    transform: [{ rotate: '50deg' }],
  },
  toothNumber11: {
    position: 'absolute',
    left: 75,
    top: '12.5%',
    transform: [{ rotate: '35deg' }],
  },
  toothNumber12: {
    position: 'absolute',
    left: 40,
    top: '19%',
    transform: [{ rotate: '15deg' }],
  },
  toothNumber13: {
    position: 'absolute',
    left: 30,
    top: '23.5%',
    transform: [{ rotate: '15deg' }],
  },
  toothNumber14: {
    position: 'absolute',
    left: 20,
    top: '31.5%',
  },
  toothNumber15: {
    position: 'absolute',
    left: 20,
    top: '37.5%',
  },
  toothNumber16: {
    position: 'absolute',
    left: 20,
    top: '43.5%',
  },
  // Tooth Numbers 17-24
  toothNumber17: {
    position: 'absolute',
    right: 165,
    bottom: '5%',
    transform: [{ rotate: '80deg' }],
  },
  toothNumber18: {
    position: 'absolute',
    right: 115,
    bottom: '8.5%',
    transform: [{ rotate: '50deg' }],
  },
  toothNumber19: {
    position: 'absolute',
    right: 75,
    bottom: '12.5%',
    transform: [{ rotate: '35deg' }],
  },
  toothNumber20: {
    position: 'absolute',
    right: 40,
    bottom: '19%',
    transform: [{ rotate: '15deg' }],
  },
  toothNumber21: {
    position: 'absolute',
    right: 30,
    bottom: '23.5%',
    transform: [{ rotate: '15deg' }],
  },
  toothNumber22: {
    position: 'absolute',
    right: 20,
    bottom: '31.5%',
  },
  toothNumber23: {
    position: 'absolute',
    right: 20,
    bottom: '37.5%',
  },
  toothNumber24: {
    position: 'absolute',
    right: 20,
    bottom: '43.5%',
  },
  // Tooth Numbers 25-32
  toothNumber25: {
    position: 'absolute',
    left: 165,
    bottom: '5%',
    transform: [{ rotate: '-80deg' }],
  },
  toothNumber26: {
    position: 'absolute',
    left: 115,
    bottom: '8.5%',
    transform: [{ rotate: '-50deg' }],
  },
  toothNumber27: {
    position: 'absolute',
    left: 75,
    bottom: '12.5%',
    transform: [{ rotate: '-35deg' }],
  },
  toothNumber28: {
    position: 'absolute',
    left: 40,
    bottom: '19%',
    transform: [{ rotate: '-15deg' }],
  },
  toothNumber29: {
    position: 'absolute',
    left: 30,
    bottom: '23.5%',
    transform: [{ rotate: '-15deg' }],
  },
  toothNumber30: {
    position: 'absolute',
    left: 20,
    bottom: '31.5%',
  },
  toothNumber31: {
    position: 'absolute',
    left: 20,
    bottom: '37.5%',
  },
  toothNumber32: {
    position: 'absolute',
    left: 20,
    bottom: '43.5%',
  },
  toothNumberText: {
    fontSize: 14,
    fontWeight: '700',
    color: 'rgba(135, 206, 250, 0.95)',
  },
  toothGradient: {
    width: '100%',
    height: '100%',
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toothOval: {
    width: '100%',
    height: '100%',
    borderRadius: 20,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
    backgroundColor: 'transparent',
    alignItems: 'center',
    justifyContent: 'center',
  },
  toothNumber: {
    fontSize: 18,
    fontWeight: '700',
    color: '#5B9FED',
  },
  // Condition Menu Styles
  conditionMenuOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.6)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  conditionMenuContainer: {
    borderRadius: 20,
    marginHorizontal: 8,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    overflow: 'hidden',
  },
  conditionMenuTitle: {
    fontSize: 22,
    fontWeight: '700',
    color: '#1E3A8A',
    textAlign: 'center',
  },
  conditionMenuSubtitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#3B82F6',
    textAlign: 'center',
    marginTop: 6,
  },
  conditionModalHeaderContent: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  conditionMenuDivider: {
    height: 1.5,
    backgroundColor: 'rgba(59, 130, 246, 0.3)',
    marginBottom: 12,
    marginHorizontal: 16,
  },
  conditionMenuScroll: {
    maxHeight: 450,
  },
  conditionMenuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    marginHorizontal: 12,
    marginVertical: 6,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.6)',
  },
  conditionColorBox: {
    width: 14,
    height: 14,
    borderRadius: 7,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  conditionMenuItemText: {
    fontSize: 16,
    color: '#1E293B',
    fontWeight: '600',
    marginLeft: 14,
  },
  // Enlarged Tooth Overlay Styles
  enlargedToothOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.85)',
    justifyContent: 'center',
    alignItems: 'center',
  },
  enlargedToothCloseButton: {
    position: 'absolute',
    top: 50,
    right: 20,
    zIndex: 1000,
    width: 60,
    height: 60,
    borderRadius: 30,
    backgroundColor: 'rgba(255, 82, 82, 0.9)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 8,
  },
  enlargedToothContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 30,
    justifyContent: 'center',
    alignItems: 'center',
    padding: 40,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 10 },
    shadowOpacity: 0.5,
    shadowRadius: 30,
    elevation: 20,
  },
  enlargedToothNumberBadge: {
    position: 'absolute',
    top: 20,
    backgroundColor: 'rgba(91, 159, 237, 0.95)',
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 20,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  enlargedToothNumberText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
  },
  toothDetailsScrollView: {
    flex: 1,
  },
  toothDetailsScrollContent: {
    padding: 20,
    paddingTop: 10,
  },
  toothDetailsContainer: {
    flex: 1,
  },
  toothDetailsHeaderCard: {
    borderRadius: 16,
    padding: 20,
    marginBottom: 20,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  toothDetailsMainTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 10,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  toothDetailsSubtitle: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.8)',
    textAlign: 'center',
    marginTop: 5,
  },
  emptyStateCard: {
    borderRadius: 16,
    padding: 40,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  emptyStateText: {
    fontSize: 18,
    fontWeight: '600',
    color: '#FFFFFF',
    textAlign: 'center',
    marginTop: 20,
  },
  emptyStateSubtext: {
    fontSize: 14,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.7)',
    textAlign: 'center',
    marginTop: 5,
  },
  toothCard: {
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  toothCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 12,
    gap: 12,
  },
  toothNumberBadge: {
    width: 50,
    height: 50,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.25)',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 3,
    borderColor: 'transparent',
  },
  quadrantUpperLeft: {
    borderBottomColor: 'rgba(255, 255, 255, 0.8)',
    borderLeftColor: 'rgba(255, 255, 255, 0.8)',
  },
  quadrantUpperRight: {
    borderTopColor: 'rgba(255, 255, 255, 0.8)',
    borderRightColor: 'rgba(255, 255, 255, 0.8)',
  },
  quadrantLowerLeft: {
    borderBottomColor: 'rgba(255, 255, 255, 0.8)',
    borderLeftColor: 'rgba(255, 255, 255, 0.8)',
  },
  quadrantLowerRight: {
    borderBottomColor: 'rgba(255, 255, 255, 0.8)',
    borderRightColor: 'rgba(255, 255, 255, 0.8)',
  },
  toothNumberBadgeText: {
    fontSize: 20,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  toothInfoContainer: {
    flex: 1,
    justifyContent: 'center',
  },
  toothNameText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  toothNameEnglishText: {
    fontSize: 12,
    fontWeight: '400',
    color: 'rgba(255, 255, 255, 0.8)',
    marginTop: 2,
  },
  conditionBadgesContainer: {
    flexDirection: 'column',
    gap: 6,
    alignItems: 'flex-end',
  },
  conditionBadge: {
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  conditionBadgeText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  toothPositionContainer: {
    flex: 1,
  },
  toothPositionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  surfaceItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.30)',
    borderRadius: 12,
    padding: 12,
    gap: 8,
  },
  toothDetailsContent: {
    backgroundColor: 'rgba(255, 255, 255, 0.30)',
    borderRadius: 12,
    padding: 12,
    gap: 10,
  },
  conditionsSection: {
    gap: 8,
    marginBottom: 8,
  },
  conditionChip: {
    backgroundColor: 'rgba(100, 181, 246, 0.2)',
    borderRadius: 8,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderWidth: 1,
    borderColor: 'rgba(100, 181, 246, 0.3)',
  },
  conditionChipText: {
    fontSize: 12,
    color: '#2C3E50',
    fontWeight: '500',
  },
  surfaceDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    marginBottom: 4,
  },
  surfaceNameText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#2C3E50',
    marginBottom: 6,
  },
  surfaceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  surfaceLabel: {
    fontSize: 14,
    fontWeight: '600',
    color: '#2C3E50',
    minWidth: 60,
  },
  surfaceValue: {
    fontSize: 14,
    fontWeight: '400',
    color: '#34495E',
    flex: 1,
  },
  dropdownContainer: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 254, 230, 0.75)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
  },
  dropdownPlaceholder: {
    fontSize: 14,
    fontWeight: '500',
    color: '#6B7280',
  },
  labelInput: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    fontSize: 14,
    fontWeight: '500',
    color: '#2C3E50',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
  },
  labelInputDisabled: {
    backgroundColor: 'rgba(209, 213, 219, 0.3)',
    color: '#9CA3AF',
  },
  dropdownModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  dropdownModalContent: {
    backgroundColor: 'rgba(240, 249, 255, 0.98)',
    borderRadius: 24,
    padding: 22,
    width: '100%',
    maxHeight: '92%',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    elevation: 5,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    } : {}),
  },
  dropdownOption: {
    paddingVertical: 12,
    paddingHorizontal: 12,
    borderRadius: 8,
    marginVertical: 4,
    backgroundColor: 'rgba(255, 252, 220, 0.9)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  dropdownOptionSelected: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderColor: 'rgba(59, 130, 246, 0.5)',
  },
  dropdownOptionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2C3E50',
  },
  dropdownOptionTextSelected: {
    color: '#3B82F6',
  },
  dropdownTitle: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2C3E50',
    marginBottom: 12,
    textAlign: 'center' as const,
  },
  dropdownDoneButton: {
    backgroundColor: '#3B82F6',
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    marginTop: 12,
    alignItems: 'center',
  },
  dropdownDoneButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  conditionIndicator: {
    width: 18,
    height: 18,
    borderRadius: 9,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  actionButtonsContainer: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    gap: 8,
    marginTop: 16,
    paddingHorizontal: 12,
    paddingBottom: 12,
  },
  actionButton: {
    flex: 1,
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 254, 230, 0.75)',
    borderRadius: 10,
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    gap: 4,
  },
  actionButtonText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
  },
  actionButtonActive: {
    borderColor: '#3B82F6',
    borderWidth: 2,
  },
  actionButtonTextActive: {
    color: '#3B82F6',
  },
  actionButtonDisabled: {
    opacity: 0.5,
  },
  dropdownDisabled: {
    opacity: 0.5,
  },
  notesContainer: {
    padding: 16,
  },
  notesTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 12,
  },
  notesInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#2C3E50',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    minHeight: 120,
    textAlignVertical: 'top',
  },
  recordsContainer: {
    padding: 16,
  },
  recordsTitle: {
    fontSize: 15,
    fontWeight: '600',
    color: '#2C3E50',
    marginBottom: 12,
  },
  recordsList: {
    maxHeight: 200,
  },
  noRecordsText: {
    fontSize: 14,
    color: '#9CA3AF',
    fontStyle: 'italic',
    textAlign: 'center',
    paddingVertical: 20,
  },
  recordItem: {
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 8,
    padding: 12,
    marginBottom: 8,
    borderLeftWidth: 3,
    borderLeftColor: '#3B82F6',
  },
  recordText: {
    fontSize: 13,
    color: '#2C3E50',
    marginBottom: 4,
    lineHeight: 18,
  },
  addNoteContainer: {
    marginTop: 12,
    gap: 8,
  },
  addNoteInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    borderRadius: 8,
    padding: 12,
    color: '#2C3E50',
    fontSize: 14,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    minHeight: 80,
    textAlignVertical: 'top',
  },
  addNoteButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(59, 130, 246, 0.3)',
  },
  addNoteButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#3B82F6',
  },
  noteBadge: {
    position: 'absolute',
    top: -2,
    right: -2,
  },
  noteBadgeDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: '#EF4444',
  },
  // New Modal Styles
  newModalContainer: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    overflow: 'hidden',
    elevation: 8,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
    } : {}),
  },
  newModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  toothNumberBox: {
    backgroundColor: 'rgba(96, 165, 250, 0.2)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    elevation: 2,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    } : {}),
  },
  modalToothNumberText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E3A8A',
  },
  modalToothNameText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A8A',
  },
  editButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  editButtonActive: {
    backgroundColor: '#60A5FA',
    borderColor: '#3B82F6',
    borderWidth: 2,
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {}),
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  closeButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  modalContent: {
    flexGrow: 0,
    flexShrink: 1,
    paddingHorizontal: 16,
    paddingTop: 16,
  },
  mainSectionsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    padding: 18,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    } : {}),
  },
  whiteSection: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    padding: 18,
    marginBottom: 12,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    } : {}),
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  sectionLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginVertical: 8,
  },
  dropdownInput: {
    width: 170,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.5)',
  },
  dropdownInputActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    elevation: 2,
  },
  dropdownText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
  },
  expandedOptions: {
    marginTop: 8,
    maxHeight: 180,
    zIndex: 1000,
    elevation: 10,
  },
  dropdownModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E3A8A',
    marginBottom: 18,
    textAlign: 'center',
  },
  dropdownModalList: {
    maxHeight: 800,
  },
  dropdownModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.4)',
    marginBottom: 12,
    elevation: 1,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    } : {}),
  },
  optionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    padding: 12,
    borderRadius: 10,
    borderWidth: 1.5,
    borderColor: 'rgba(203, 213, 225, 0.4)',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: 4,
    borderWidth: 2,
    borderColor: '#94A3B8',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  checkboxSelected: {
    borderColor: '#0284C7',
    backgroundColor: '#0284C7',
  },
  checkboxChecked: {
    backgroundColor: '#3B82F6',
    borderColor: '#3B82F6',
  },
  checkmark: {
    color: '#FFFFFF',
  },
  optionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  radioButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#94A3B8',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  radioButtonSelected: {
    borderColor: '#60A5FA',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#60A5FA',
  },
  headerDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 16,
  },
  // Tab Buttons Styles
  tabButtons: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
    backgroundColor: 'rgba(248, 250, 252, 0.9)',
    borderRadius: 16,
    marginHorizontal: 4,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(203, 213, 225, 0.6)',
  },
  tabBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    gap: 6,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.6)',
    elevation: 1,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    } : {}),
  },
  tabBtnActive: {
    backgroundColor: '#3B82F6',
    borderWidth: 2,
    borderColor: '#2563EB',
    elevation: 4,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    } : {}),
  },
  tabBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.3,
  },
  tabBtnTextActive: {
    color: '#FFFFFF',
  },
  // Submit Button Styles
  submitButtonContainer: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: 'rgba(248, 250, 252, 0.7)',
    borderTopWidth: 2,
    borderTopColor: 'rgba(203, 213, 225, 0.6)',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(226, 232, 240, 0.7)',
    gap: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  submitButtonActive: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
    borderWidth: 2,
    elevation: 6,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
    } : {}),
  },
  submitButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.5,
  },
  surfacesGrid: {
    minHeight: 60,
  },
  treatmentContainer: {
    minHeight: 50,
  },
  detailsContainer: {
    minHeight: 50,
  },
  placeholderText: {
    fontSize: 14,
    color: '#64748B',
    fontStyle: 'italic',
  },
  bottomButtons: {
    flexDirection: 'row',
    backgroundColor: 'transparent',
    paddingVertical: 8,
    paddingHorizontal: 8,
    gap: 8,
  },
  bottomBtn: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    gap: 4,
  },
  bottomBtnActive: {
    backgroundColor: '#10B981',
  },
  bottomBtnText: {
    fontSize: 11,
    fontWeight: '600',
    color: '#1E3A8A',
  },
  // Surfaces Modal Styles
  surfacesModalBox: {
    width: '85%',
    backgroundColor: 'rgba(96, 165, 250, 0.3)',
    borderRadius: 20,
    borderWidth: 1,
    borderColor: '#FFFFFF',
    padding: 20,
  },
  surfacesModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 20,
  },
  surfacesModalTitle: {
    fontSize: 20,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  surfacesList: {
    gap: 12,
    marginBottom: 20,
  },
  surfaceCheckBox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 2,
    borderColor: '#FFFFFF',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'transparent',
  },
  surfaceCheckBoxSelected: {
    backgroundColor: '#60A5FA',
    borderColor: '#60A5FA',
  },
  surfaceItemText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  surfacesDoneBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    padding: 16,
    borderRadius: 12,
    alignItems: 'center',
  },
  surfacesDoneBtnText: {
    fontSize: 16,
    fontWeight: 'bold',
    color: '#FFFFFF',
  },
  // Notes Section Styles
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -8,
    backgroundColor: '#EF4444',
    borderRadius: 10,
    minWidth: 18,
    height: 18,
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 4,
  },
  notificationBadgeText: {
    color: '#FFFFFF',
    fontSize: 10,
    fontWeight: 'bold',
  },
  notesSection: {
    gap: 14,
  },
  savedNotesContainer: {
    gap: 10,
  },
  noteCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
    borderWidth: 1.5,
    borderColor: 'rgba(203, 213, 225, 0.5)',
    elevation: 2,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    } : {}),
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  noteDoctorName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
  },
  noteTimestamp: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
  },
  noteText: {
    fontSize: 14,
    color: '#334155',
    lineHeight: 20,
  },
  newNoteContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.35)',
  },
  noteInput: {
    fontSize: 14,
    color: '#1E293B',
    minHeight: 70,
    textAlignVertical: 'top',
    fontWeight: '500',
  },
  // Records Section Styles
  recordsMainContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    } : {}),
    padding: 16,
    gap: 12,
  },
  recordsTypeButtons: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
    justifyContent: 'center',
  },
  recordsTypeBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.6)',
  },
  recordsTypeBtnActive: {
    backgroundColor: '#3B82F6',
    borderColor: '#2563EB',
    borderWidth: 2,
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {}),
  },
  recordsTypeBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.2,
  },
  recordsTypeBtnTextActive: {
    color: '#FFFFFF',
  },
  recordCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
    borderWidth: 1.5,
    borderColor: 'rgba(203, 213, 225, 0.5)',
    gap: 10,
    elevation: 2,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 4,
    } : {}),
  },
  recordHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  recordDoctorName: {
    fontSize: 13,
    fontWeight: '600',
    color: '#1E293B',
  },
  recordTimestamp: {
    fontSize: 11,
    color: '#64748B',
  },
  recordRow: {
    flexDirection: 'row',
    gap: 8,
  },
  recordLabel: {
    fontSize: 12,
    fontWeight: '600',
    color: '#475569',
    minWidth: 70,
  },
  recordValue: {
    fontSize: 12,
    color: '#1E293B',
    flex: 1,
  },
  noRecordsContainer: {
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 40,
    gap: 12,
  },
  planningRecordContent: {
    paddingTop: 4,
  },
  planningRecordText: {
    fontSize: 13,
    color: '#1E293B',
    lineHeight: 20,
  },
  planningRecordHighlight: {
    fontWeight: '600',
    color: '#3B82F6',
  },
  referralContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 90,
    paddingHorizontal: 20,
    zIndex: 10003,
  },
  referralTouchable: {
    width: '90%',
    maxWidth: 400,
  },
  referralContent: {
    borderRadius: 24,
    padding: 28,
    borderWidth: 3,
    borderColor: 'rgba(186, 230, 253, 0.6)',
    backgroundColor: 'rgba(240, 249, 255, 0.25)',
    shadowColor: '#7DD3FC',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
    overflow: 'hidden',
  },
  referralHeader: {
    marginBottom: 18,
    paddingBottom: 12,
    borderBottomWidth: 2,
    borderBottomColor: 'rgba(186, 230, 253, 0.3)',
  },
  referralTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#7DD3FC',
    textAlign: 'center',
    textShadowColor: 'rgba(125, 211, 252, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  referralItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 14,
    paddingHorizontal: 18,
    marginBottom: 12,
    borderRadius: 14,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderWidth: 1,
    borderColor: 'rgba(186, 230, 253, 0.4)',
  },
  referralItemSelected: {
    backgroundColor: 'rgba(186, 230, 253, 0.3)',
    borderColor: 'rgba(125, 211, 252, 0.8)',
    shadowColor: '#7DD3FC',
    shadowOffset: { width: 0, height: 3 },
    shadowOpacity: 0.4,
    shadowRadius: 10,
    elevation: 5,
  },
  selectedReferralsContainer: {
    marginTop: 8,
    marginBottom: 16,
    gap: 10,
  },
  selectedReferralItem: {
    flexDirection: 'column',
    paddingVertical: 12,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(186, 230, 253, 0.2)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(125, 211, 252, 0.5)',
  },
  selectedReferralName: {
    fontSize: 16,
    fontWeight: '600',
    color: '#38BDF8',
    flex: 1,
  },
  statusButton: {
    paddingHorizontal: 14,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.8)',
    borderWidth: 1.5,
    minWidth: 90,
    alignItems: 'center',
  },
  statusText: {
    fontSize: 14,
    fontWeight: '700',
  },
  statusTextGiven: {
    color: '#10B981',
  },
  statusTextNotGiven: {
    color: '#EF4444',
  },
  additionalContainer: {
    width: '90%',
    maxWidth: 400,
    marginTop: 16,
  },
  additionalContent: {
    borderRadius: 24,
    padding: 28,
    borderWidth: 3,
    borderColor: 'rgba(186, 230, 253, 0.6)',
    backgroundColor: 'rgba(240, 249, 255, 0.25)',
    shadowColor: '#7DD3FC',
    shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.4,
    shadowRadius: 16,
    elevation: 10,
    overflow: 'hidden',
  },
  additionalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#7DD3FC',
    textAlign: 'center',
    textShadowColor: 'rgba(125, 211, 252, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
    marginBottom: 0,
  },
  referralText: {
    fontSize: 16,
    color: '#0F172A',
    fontWeight: '600',
  },
  treatmentRecordContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 230,
    paddingHorizontal: 20,
    zIndex: 10002,
  },
  planningRecordContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    justifyContent: 'flex-start',
    alignItems: 'center',
    paddingTop: 340,
    paddingHorizontal: 20,
    zIndex: 10001,
  },
});

// Export screen dimensions for use in components
export { SCREEN_WIDTH, SCREEN_HEIGHT };
