// ═══════════════════════════════════════════════════════════════
// Build AI V2 prompts — compile the markdown prompt + catalog
// files under lib/ai_v2/ into a single TypeScript module that
// sendMessageV2 can import at runtime.
//
// React Native cannot read .md files at runtime, so we inline
// them into TS template literals at build time (same pattern
// as scripts/build-rag.js for V1).
//
// Usage:  node scripts/build-ai-v2.js
// Output: lib/ai_v2/_compiled.ts
//
// Exports:
//   - CORE_PROMPT_V2          (lib/ai_v2/core_prompt.md)
//   - TEAM_LEADER_PROMPT_V2   (lib/ai_v2/team_leader_prompt.md)
//   - CATALOG_V2              (lib/ai_v2/catalog.md)
//
// Re-run whenever any of these .md files change.
// ═══════════════════════════════════════════════════════════════

const fs = require('fs');
const path = require('path');

const V2_ROOT = path.join(__dirname, '..', 'lib', 'ai_v2');
const OUTPUT_FILE = path.join(V2_ROOT, '_compiled.ts');

const FILES = [
  { name: 'CORE_PROMPT_V2', file: 'core_prompt.md' },
  { name: 'TEAM_LEADER_PROMPT_V2', file: 'team_leader_prompt.md' },
  { name: 'CATALOG_V2', file: 'catalog.md' },
];

/**
 * Escape a string for embedding inside a TS template literal:
 *   backticks → \`
 *   ${ → \${
 *   backslash → \\
 */
function escapeForTemplateLiteral(text) {
  return text
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');
}

function build() {
  const sections = FILES.map(({ name, file }) => {
    const abs = path.join(V2_ROOT, file);
    if (!fs.existsSync(abs)) {
      console.error(`Missing source file: ${abs}`);
      process.exit(1);
    }
    const body = fs.readFileSync(abs, 'utf8');
    const escaped = escapeForTemplateLiteral(body);
    return `export const ${name} = \`${escaped}\`;`;
  });

  const header = [
    '// ═══════════════════════════════════════════════════════════════',
    '// DCM AI V2 — auto-generated from .md files under lib/ai_v2/',
    '// ═══════════════════════════════════════════════════════════════',
    '// DO NOT EDIT THIS FILE BY HAND.',
    '// Re-generate with:  node scripts/build-ai-v2.js',
    '//',
    `// Generated: ${new Date().toISOString()}`,
    '// ═══════════════════════════════════════════════════════════════',
    '',
  ].join('\n');

  const output = header + '\n' + sections.join('\n\n') + '\n';
  fs.writeFileSync(OUTPUT_FILE, output, 'utf8');

  const sizes = FILES.map(({ name, file }) => {
    const abs = path.join(V2_ROOT, file);
    const kb = (fs.statSync(abs).size / 1024).toFixed(1);
    return `  ${name.padEnd(22)} ← ${file.padEnd(25)} (${kb} KB)`;
  }).join('\n');

  console.log(`AI V2 prompts compiled to ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  console.log(sizes);
}

build();
