// ═══════════════════════════════════════════════════════════════
// Build RAG — compile all .md files under lib/ai/rag/ into a
// single TypeScript module that the AI service can import at
// runtime. React Native cannot read .md files at runtime, so we
// inline them into TS template literals at build time.
//
// Usage:  node scripts/build-rag.js
// Output: lib/ai/rag/_compiled.ts
//
// The output exports two constants:
//   - SHARED_KNOWLEDGE_RAG   — concatenated shared knowledge
//   - TEAM_LEADER_RAG        — concatenated TL workflows + rules + examples
//
// (DOCTOR_RAG will be added when the Doctor assistant is wired.)
//
// Re-run this script whenever any .md file under lib/ai/rag/
// changes.
// ═══════════════════════════════════════════════════════════════

const fs = require('fs');
const path = require('path');

const RAG_ROOT = path.join(__dirname, '..', 'lib', 'ai', 'rag');
const OUTPUT_FILE = path.join(RAG_ROOT, '_compiled.ts');

/**
 * Recursively collect all .md files under a directory.
 * Returns absolute file paths sorted alphabetically.
 */
function collectMarkdownFiles(dir) {
  const results = [];
  const entries = fs.readdirSync(dir, { withFileTypes: true });
  for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      results.push(...collectMarkdownFiles(full));
    } else if (entry.isFile() && entry.name.endsWith('.md')) {
      results.push(full);
    }
  }
  return results;
}

/**
 * Read a file, return its text, and produce a section header
 * showing its relative path so the AI can cite the source.
 */
function fileToSection(absPath) {
  const rel = path.relative(RAG_ROOT, absPath).split(path.sep).join('/');
  const body = fs.readFileSync(absPath, 'utf8');
  return `\n\n═══════════════════════════════════════\nFILE: ${rel}\n═══════════════════════════════════════\n${body}`;
}

/**
 * Compile one subtree into a single string.
 */
function compileSubtree(subdir) {
  const root = path.join(RAG_ROOT, subdir);
  if (!fs.existsSync(root)) return '';
  const files = collectMarkdownFiles(root);
  return files.map(fileToSection).join('');
}

/**
 * Escape backticks and ${ for TypeScript template literal.
 */
function escapeForTemplateLiteral(text) {
  return text.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');
}

function build() {
  const shared = compileSubtree('sharedKnowledge');
  const teamLeader = compileSubtree('teamLeaderKnowledge');

  const sharedFiles = collectMarkdownFiles(path.join(RAG_ROOT, 'sharedKnowledge'));
  const tlFiles = collectMarkdownFiles(path.join(RAG_ROOT, 'teamLeaderKnowledge'));

  const header = `// ═══════════════════════════════════════════════════════════════
// DCM AI RAG — auto-generated from .md files under lib/ai/rag/
// ═══════════════════════════════════════════════════════════════
// DO NOT EDIT THIS FILE BY HAND.
// Re-generate with:  node scripts/build-rag.js
//
// Generated: ${new Date().toISOString()}
// Shared knowledge files: ${sharedFiles.length}
// Team Leader knowledge files: ${tlFiles.length}
// ═══════════════════════════════════════════════════════════════

`;

  const body =
    `export const SHARED_KNOWLEDGE_RAG = \`${escapeForTemplateLiteral(shared)}\`;\n\n` +
    `export const TEAM_LEADER_RAG = \`${escapeForTemplateLiteral(teamLeader)}\`;\n`;

  fs.writeFileSync(OUTPUT_FILE, header + body, 'utf8');

  const sharedKB = Math.round(shared.length / 1024);
  const tlKB = Math.round(teamLeader.length / 1024);
  console.log(`Wrote ${path.relative(process.cwd(), OUTPUT_FILE)}`);
  console.log(`  Shared knowledge:      ${sharedFiles.length} files, ${sharedKB} KB`);
  console.log(`  Team Leader knowledge: ${tlFiles.length} files, ${tlKB} KB`);
  console.log(`  Total size: ${Math.round((shared.length + teamLeader.length) / 1024)} KB`);
}

build();
