import { StyleSheet, Platform } from 'react-native';

export const styles = StyleSheet.create({
  loadingContainer: { flex: 1, justifyContent: 'center', alignItems: 'center' },
  container: { flex: 1 },
  gradient: { flex: 1 },
  header: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 24, paddingTop: 12, paddingBottom: 20 },
  headerCenter: { flex: 1, alignItems: 'center' },
  headerTitle: { fontSize: 28, fontWeight: '700', color: '#1F2937', letterSpacing: -0.5 }, // تكبير العنوان
  headerSubtitle: { fontSize: 13, color: '#6B7280', marginTop: 2 }, // رمادي كما كان
  iconButton: { width: 44, height: 44, justifyContent: 'center', alignItems: 'center' },
  // زر البروفايل - مطابق تماماً لـ FAB
  profileButton: {
    width: 44,
    height: 44,
    borderRadius: 22,
  },
  profileButtonGlass: {
    width: '100%',
    height: '100%',
    borderRadius: 22,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  profileButtonInnerGlow: {
    position: 'absolute',
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'transparent', // إزالة Inner Glow
  },
  // زر الأرشفة الاحترافي
  archiveButton: {
    width: 44,
    height: 44,
    justifyContent: 'center',
    alignItems: 'center',
  },
  archiveButtonGradient: {
    width: 44,
    height: 44,
    borderRadius: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  statsContainer: { flexDirection: 'row', paddingHorizontal: 24, gap: 16, marginBottom: 24 },
  statCard: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.4)', // زجاجي شفاف
    borderRadius: 20,
    padding: 20,
    alignItems: 'center',
    minHeight: 150,
    justifyContent: 'center',
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)', // حواف بيضاء
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#5B9FED',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 12,
    elevation: Platform.OS === 'android' ? 0 : 5,
  },
  statCardActive: {
    backgroundColor: 'rgba(125, 211, 192, 0.3)', // زجاجي فيروزي عند التفعيل
    borderWidth: 2.5,
    borderColor: 'rgba(125, 211, 192, 0.9)', // حواف فيروزية
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#7DD3C0',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 0 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.4,
    shadowRadius: Platform.OS === 'android' ? 0 : 16,
    elevation: Platform.OS === 'android' ? 0 : 0,
  },
  statCardExpanded: {
    flex: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.4)', // زجاجي شفاف
    borderRadius: 20,
    padding: 20,
    minHeight: 200,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)', // حواف بيضاء
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#5B9FED',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 12,
    elevation: Platform.OS === 'android' ? 0 : 5,
  },
  expandedHeader: { flexDirection: 'row', alignItems: 'center', gap: 12, marginBottom: 16 },
  expandedTitle: { fontSize: 18, fontWeight: '700', color: '#4A5568' },
  treatmentStatsList: { gap: 4 },
  treatmentStatRow: { flexDirection: 'row', alignItems: 'center', paddingVertical: 6, gap: 12 },
  treatmentStatCount: { fontSize: 24, fontWeight: '700', color: '#7DD3C0', minWidth: 40 },
  treatmentStatName: { fontSize: 16, fontWeight: '500', color: '#4A5568' },
  statLabel: { fontSize: 14, color: '#6B7280', fontWeight: '400', marginBottom: 4 },
  statLabelActive: { color: '#7DD3C0', fontWeight: '600' },
  statValue: { fontSize: 52, fontWeight: '600', color: '#4A5568' },
  statValueActive: { color: '#7DD3C0' },
  queueHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 24,
    marginBottom: 12,
  },
  queueTitleContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  queueTitle: { fontSize: 32, fontWeight: '700', color: '#4A5568' },
  minimizeButton: {
    width: 45,
    height: 45,
    borderRadius: 22.5,
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    justifyContent: 'center',
    alignItems: 'center',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  minimizeButtonInnerGlow: {
    position: 'absolute',
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'transparent', // إزالة Inner Glow
  },
  // Header View Details button
  viewDetailsHeaderButton: {
    paddingHorizontal: 20,
    paddingVertical: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderRadius: 20,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  viewDetailsHeaderText: { fontSize: 14, color: '#6B7280', fontWeight: '600' },
  // Expandable section in header
  headerExpandableSection: {
    alignSelf: 'flex-end',
    marginRight: 24,
    marginBottom: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.4)',
    borderRadius: 16,
    padding: 12,
    gap: 8,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 2 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.1,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  headerOptionButton: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.4)', // زجاجي شفاف
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.8)', // حدود بيضاء لامعة
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 2 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.1,
    shadowRadius: Platform.OS === 'android' ? 0 : 4,
    elevation: Platform.OS === 'android' ? 0 : 3,
  },
  headerOptionButtonActive: {
    backgroundColor: 'rgba(125, 211, 192, 0.3)', // زجاجي فيروزي عند التفعيل
    borderWidth: 2.5,
    borderColor: 'rgba(125, 211, 192, 0.9)', // حدود فيروزية لامعة
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#7DD3C0',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 3 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.3,
    shadowRadius: Platform.OS === 'android' ? 0 : 6,
    elevation: Platform.OS === 'android' ? 0 : 5,
  },
  headerOptionText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#6B7280',
  },
  headerOptionTextActive: {
    color: '#7DD3C0',
  },
  scrollView: { flex: 1 },
  scrollContent: { paddingHorizontal: 24, paddingTop: 0, paddingBottom: 120 },
  patientCardWrapper: {
    flexDirection: 'row',
    position: 'relative', // للسماح بـ absolute positioning للـ Queue Number
    marginBottom: 16,
    borderRadius: 18,
    overflow: 'hidden',
    backgroundColor: 'rgba(255, 255, 255, 0.35)', // زجاجي شفاف
    borderWidth: 2.5, // حواف أعرض
    borderColor: 'rgba(255, 255, 255, 0.7)', // حواف بيضاء (افتراضي)
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#5B9FED',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 2 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.1,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 3,
  },
  queueNumberSection: {
    flex: 1,
    width: 50,
    justifyContent: 'center',
    alignItems: 'center',
    // نفس الشكل الأصلي - فقط اللون زجاجي
  },
  patientCardContent: {
    flex: 1,
    paddingTop: 10,
    paddingBottom: 10,
    paddingLeft: 10,
    paddingRight: 0, // لا فراغ من اليمين ليتصل مع القيو نمبر
  },
  cardHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 6 },
  leftSection: { flexDirection: 'row', alignItems: 'center', gap: 6 },
  // Old badge styles - replaced with CircularBadge component
  // statusBadge: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 12, minWidth: 50, maxWidth: 70, alignItems: 'center', justifyContent: 'center' },
  // statusBadgeText: { fontSize: 11, fontWeight: '700', color: '#FFFFFF', textAlign: 'center' },
  queueNumberText: { fontSize: 17, fontWeight: '700', color: '#FFFFFF' },
  patientName: {
    fontSize: 18,
    fontWeight: '700',
    color: '#2D3748',
    letterSpacing: 0.3,
    fontFamily: 'Cairo-Bold', // خط Cairo Bold
    marginLeft: 70, // مسافة من اليسار
    marginRight: 20, // إبعاد الاسم 20px عن الحافة اليمنى
  },
  divider: { height: 3, backgroundColor: 'rgba(255, 255, 255, 0.4)', marginBottom: 6 }, // أبيض شفاف أعرض (3px)
  tagsRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 8, paddingHorizontal: 4 },
  tag: {
    flex: 1,
    paddingHorizontal: 8,
    paddingVertical: 6,
    borderRadius: 12,
    minWidth: 0,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)', // Glass effect شفاف أكثر
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.3)',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 2 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.1,
    shadowRadius: Platform.OS === 'android' ? 0 : 4,
    elevation: Platform.OS === 'android' ? 0 : 2,
  },
  tagText: { fontSize: 12, fontWeight: '600', color: '#4A5568', textAlign: 'center' },
  menuButton: {
    width: 32,
    height: 32,
    borderRadius: 16,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    alignItems: 'center',
    justifyContent: 'center',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  menuIcon: {
    fontSize: 18,
    fontWeight: '700',
    textAlign: 'center',
    ...(Platform.OS === 'android' ? { marginTop: -3 } : { lineHeight: 32 }),
  },
  timelineContainer: { flexDirection: 'row', alignItems: 'center', marginTop: 8, gap: 6 },
  timelineText: { fontSize: 12, color: '#9CA3AF', fontWeight: '500' },
  fab: { position: 'absolute', bottom: 15, right: 24, width: 68, height: 68, borderRadius: 34 },
  fabGlass: {
    width: '100%',
    height: '100%',
    borderRadius: 34,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.2,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 4,
  },
  fabInnerGlow: {
    position: 'absolute',
    width: 48,
    height: 48,
    borderRadius: 24,
    backgroundColor: 'transparent', // إزالة Inner Glow
  },
  fabIcon: {
    fontSize: 42,
    color: '#7DD3C0', // فيروزي لتطابق التصميم
    fontWeight: '400',
    lineHeight: 42,
    textAlign: 'center',
    textAlignVertical: 'center',
    marginTop: -2,
    zIndex: 10
  },
  bottomNav: { flexDirection: 'row', paddingVertical: 10, paddingBottom: 20, backgroundColor: 'transparent', borderTopWidth: 1.5, borderTopColor: 'rgba(255, 255, 255, 0.5)' },
  navItem: { flex: 1, alignItems: 'center', justifyContent: 'center', paddingVertical: 6 },
  navLabel: { fontSize: 11, color: '#9CA3AF', marginTop: 4, fontWeight: '500' },
  navLabelActive: { color: '#7DD3C0', fontWeight: '600' },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 50,
  },
  modalContent: {
    width: '100%',
    maxHeight: '85%',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Frosted glass effect
    borderRadius: 24,
    borderWidth: 3,
    borderColor: '#FFFFFF',
    padding: 20,
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#000',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 20 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.4,
    shadowRadius: Platform.OS === 'android' ? 0 : 30,
    elevation: Platform.OS === 'android' ? 0 : 15,
    overflow: 'hidden',
  },
  modalGlassOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    borderRadius: 24,
  },
  dropdownModal: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)', // Glass effect
    borderRadius: 20,
    width: '85%',
    maxHeight: '70%',
    overflow: 'hidden',
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
  },
  modalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 24,
  },
  modalTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#FFFFFF', // أبيض مثل Edit Modal
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  modalCloseButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.5)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  inputLabel: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF', // أبيض مثل Edit Modal
    marginBottom: 8,
    marginTop: 8,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  textInput: {
    backgroundColor: 'rgba(255, 255, 255, 0.65)', // Glass effect أعتم للوضوح
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.8)',
    borderRadius: 12,
    padding: 16,
    fontSize: 16,
    color: '#1F2937',
    fontWeight: '600',
    marginBottom: 12,
    justifyContent: 'center',
  },
  inputContainer: {
    position: 'relative',
    marginBottom: 0,
  },
  clearButton: {
    position: 'absolute',
    right: 12,
    top: 16,
    padding: 4,
    zIndex: 10,
  },
  clearButtonTextArea: {
    top: 12,
  },
  // Suggestions/Auto-complete styles
  suggestionsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(125, 211, 192, 0.6)',
    marginBottom: 16,
    marginTop: -8,
    maxHeight: 250,
    shadowColor: '#7DD3C0',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.2,
    shadowRadius: 8,
    elevation: 4,
    overflow: 'hidden',
  },
  suggestionsHeader: {
    fontSize: 12,
    fontWeight: '600',
    color: '#6B7280',
    paddingHorizontal: 16,
    paddingTop: 12,
    paddingBottom: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.95)',
  },
  suggestionsList: {
    flexGrow: 0,
    flexShrink: 1,
  },
  suggestionItem: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: 'rgba(229, 231, 235, 0.5)',
  },
  suggestionItemSelected: {
    backgroundColor: 'rgba(125, 211, 192, 0.2)',
  },
  suggestionItemText: {
    fontSize: 15,
    fontWeight: '500',
    color: '#1F2937',
    flex: 1,
  },
  expandButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 8,
    paddingVertical: 14,
    paddingHorizontal: 16,
    backgroundColor: 'rgba(125, 211, 192, 0.3)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(125, 211, 192, 0.6)',
    marginVertical: 16,
  },
  expandButtonText: {
    fontSize: 15,
    fontWeight: '600',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  modeButtonsContainer: {
    flexDirection: 'row',
    gap: 10,
    paddingHorizontal: 20,
    marginBottom: 16,
  },
  modeButton: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    gap: 6,
    paddingVertical: 14,
    paddingHorizontal: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 12,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    minHeight: 48,
  },
  modeButtonActive: {
    backgroundColor: 'rgba(125, 211, 192, 0.4)',
    borderColor: 'rgba(125, 211, 192, 0.8)',
  },
  modeButtonText: {
    fontSize: 13,
    fontWeight: '600',
    color: 'rgba(255, 255, 255, 0.7)',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
    textAlign: 'center',
    flexShrink: 1,
  },
  modeButtonTextActive: {
    color: '#FFFFFF',
  },
  textArea: { minHeight: 100, paddingTop: 16 },
  pickerContainer: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginBottom: 16 },
  pickerOption: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderRadius: 8,
    backgroundColor: 'rgba(255, 255, 255, 0.7)', // أعتم للوضوح
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.9)',
  },
  pickerOptionSelected: { backgroundColor: '#7DD3C0', borderColor: '#7DD3C0' },
  pickerOptionText: { fontSize: 14, color: '#4A5568', fontWeight: '500' },
  pickerOptionTextSelected: { color: '#FFFFFF', fontWeight: '600' },
  checkboxRow: { flexDirection: 'row', alignItems: 'center', marginBottom: 20 },
  checkbox: {
    width: 24,
    height: 24,
    borderRadius: 6,
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    justifyContent: 'center',
    alignItems: 'center',
    marginRight: 12,
  },
  checkboxChecked: { backgroundColor: '#7DD3C0', borderColor: '#7DD3C0', borderWidth: 2 },
  checkboxLabel: {
    fontSize: 16,
    color: '#FFFFFF', // أبيض مثل Edit Modal
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  addButton: {
    marginTop: 32,
    marginBottom: 16,
    borderRadius: 16,
    backgroundColor: 'rgba(125, 211, 192, 0.3)', // Glass effect فيروزي
    borderWidth: 2,
    borderColor: 'rgba(125, 211, 192, 0.6)',
    paddingVertical: 16,
    alignItems: 'center',
    shadowColor: Platform.OS === 'android' ? 'transparent' : '#7DD3C0',
    shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 4 },
    shadowOpacity: Platform.OS === 'android' ? 0 : 0.3,
    shadowRadius: Platform.OS === 'android' ? 0 : 8,
    elevation: Platform.OS === 'android' ? 0 : 6,
  },
  addButtonGradient: { paddingVertical: 16, alignItems: 'center' },
  addButtonText: {
    fontSize: 18,
    fontWeight: '700',
    color: '#FFFFFF',
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  menuModal: {
    borderRadius: 24,
    padding: 12,
    width: '75%',
    maxWidth: 300,
    alignSelf: 'center', // لتوسيع النافذة
    backgroundColor: 'rgba(255, 255, 255, 0.5)', // Glass effect أقل شفافية
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.4,
    shadowRadius: 30,
    elevation: 15,
    overflow: 'hidden',
  },
  menuItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingVertical: 16,
    paddingHorizontal: 18,
    gap: 14,
    borderRadius: 12,
    marginVertical: 4,
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  menuItemText: {
    fontSize: 16,
    color: '#FFFFFF', // أبيض مثل Edit Modal
    fontWeight: '600',
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  menuItemDanger: {
    backgroundColor: 'rgba(254, 226, 226, 0.5)',
  },
  noteText: {
    fontSize: 16,
    color: '#FFFFFF', // أبيض مثل Edit Modal
    lineHeight: 24,
    marginBottom: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  deleteButton: { backgroundColor: '#ef4444', borderRadius: 12, padding: 16, alignItems: 'center' },
  deleteButtonText: { fontSize: 16, fontWeight: '600', color: '#FFFFFF' },
  timelineScreenContainer: { flex: 1, backgroundColor: '#E8F5F0' },
  timelineHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', paddingHorizontal: 20, paddingVertical: 16 },
  timelineTitle: { fontSize: 20, fontWeight: '700', color: '#1F2937' },
  timelineContent: { flex: 1, paddingHorizontal: 20 },
  timelineEvent: { padding: 16, marginBottom: 12, backgroundColor: '#FFFFFF', borderRadius: 16 },
  eventType: { fontSize: 16, fontWeight: '700', color: '#667eea', marginBottom: 8 },
  eventDetails: { fontSize: 14, color: '#1F2937', marginBottom: 8 },
  eventDoctor: { fontSize: 12, color: '#6B7280', marginBottom: 4 },
  eventAssignedBy: { fontSize: 12, color: '#9CA3AF', fontStyle: 'italic', marginBottom: 4 },
  eventTime: { fontSize: 12, color: '#9CA3AF' },
  treatmentSection: { padding: 20, margin: 20, marginBottom: 10, backgroundColor: '#FFFFFF', borderRadius: 16 },
  treatmentInput: { backgroundColor: '#F3F4F6', borderRadius: 12, padding: 14, fontSize: 16, marginBottom: 12, minHeight: 80, textAlignVertical: 'top', borderWidth: 1, borderColor: '#E2E8F0' },
  dropdownButtonText: { fontSize: 16, color: '#1F2937', fontWeight: '500' },
  dropdownList: { backgroundColor: 'rgba(255, 255, 255, 0.4)', borderRadius: 12, marginBottom: 12, maxHeight: 200, borderWidth: 1, borderColor: 'rgba(255, 255, 255, 0.6)', shadowColor: Platform.OS === 'android' ? 'transparent' : '#000', shadowOffset: { width: 0, height: Platform.OS === 'android' ? 0 : 2 }, shadowOpacity: Platform.OS === 'android' ? 0 : 0.1, shadowRadius: Platform.OS === 'android' ? 0 : 4, elevation: Platform.OS === 'android' ? 0 : 3 },
  dropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 16,
    paddingHorizontal: 16,
    minHeight: 50,
    backgroundColor: 'transparent',
  },
  dropdownItemSelected: { backgroundColor: 'rgba(125, 211, 192, 0.2)' },
  dropdownItemText: { fontSize: 16, color: '#374151', fontWeight: '500' },
  dropdownItemTextSelected: { color: '#7DD3C0', fontWeight: '600' },
  pickerModalOverlay: { flex: 1, backgroundColor: 'rgba(0, 0, 0, 0.5)', justifyContent: 'flex-end' },
  pickerModalContent: { backgroundColor: '#FFFFFF', borderTopLeftRadius: 24, borderTopRightRadius: 24, maxHeight: '70%', paddingBottom: 34 },
  pickerHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', padding: 20, borderBottomWidth: 1, borderBottomColor: '#E2E8F0' },
  pickerTitle: { fontSize: 18, fontWeight: '700', color: '#2D3748' },
  pickerDoneButton: { fontSize: 16, fontWeight: '600', color: '#7DD3C0' },
  pickerItem: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', padding: 16, borderBottomWidth: 1, borderBottomColor: '#F7FAFC' },
  pickerItemSelected: { backgroundColor: '#F0FDF9' },
  pickerItemText: { fontSize: 16, color: '#4A5568' },
  pickerItemTextSelected: { color: '#7DD3C0', fontWeight: '600' },
  beautifulModal: {
    borderRadius: 24,
    width: '85%',
    maxHeight: '60%',
    alignSelf: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.5)', // Glass effect أقل شفافية
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.6)',
    padding: 24,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 20 },
    shadowOpacity: 0.4,
    shadowRadius: 30,
    elevation: 15,
    overflow: 'hidden',
  },
  modalHeaderTitle: {
    fontSize: 26,
    fontWeight: '700',
    color: '#FFFFFF', // أبيض مثل Edit Modal
    textAlign: 'center',
    paddingVertical: 20,
    paddingHorizontal: 24,
    textShadowColor: 'rgba(0, 0, 0, 0.3)',
    textShadowOffset: { width: 0, height: 2 },
    textShadowRadius: 4,
  },
  modalDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  modalScrollView: {
    maxHeight: 400,
  },
  beautifulDropdownItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    marginHorizontal: 8,
    marginVertical: 4,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.2)', // Glass effect
    borderWidth: 1.5,
    borderColor: 'rgba(255, 255, 255, 0.4)',
  },
  beautifulDropdownText: {
    fontSize: 16,
    color: '#FFFFFF', // أبيض مثل Edit Modal
    fontWeight: '600',
    marginLeft: 12,
    textShadowColor: 'rgba(0, 0, 0, 0.2)',
    textShadowOffset: { width: 0, height: 1 },
    textShadowRadius: 2,
  },
  colorDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
  },
  // Expandable content styles
  viewDetailsButton: {
    marginTop: 10,
    paddingVertical: 8,
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    borderRadius: 8,
  },
  viewDetailsText: {
    fontSize: 12,
    fontWeight: '600',
    color: '#4A5568',
  },
  expandableContent: {
    position: 'absolute',
    top: '100%',
    left: 0,
    right: 0,
    backgroundColor: '#FFFFFF',
    borderRadius: 18,
    marginTop: 8,
    padding: 16,
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.15,
    shadowRadius: 12,
    elevation: 8,
    zIndex: 1000,
  },
  toggleContainer: {
    flexDirection: 'row',
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    padding: 4,
    marginBottom: 16,
  },
  toggleButton: {
    flex: 1,
    paddingVertical: 10,
    alignItems: 'center',
    borderRadius: 8,
  },
  toggleButtonActive: {
    backgroundColor: '#FFFFFF',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
  },
  toggleButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#9CA3AF',
  },
  toggleButtonTextActive: {
    color: '#4A5568',
  },
  timelineEventsContainer: {
    gap: 12,
  },
  timelineEventItem: {
    flexDirection: 'row',
    gap: 12,
  },
  timelineEventDot: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#7DD3C0',
    marginTop: 4,
  },
  timelineEventContent: {
    flex: 1,
    gap: 4,
  },
  timelineEventType: {
    fontSize: 14,
    fontWeight: '700',
    color: '#2D3748',
    textTransform: 'capitalize',
  },
  timelineEventDetails: {
    fontSize: 13,
    color: '#4A5568',
    lineHeight: 18,
  },
  timelineEventDoctor: {
    fontSize: 12,
    color: '#7DD3C0',
    fontWeight: '600',
  },
  timelineEventTime: {
    fontSize: 11,
    color: '#9CA3AF',
  },
  timelineBlob: {
    position: 'absolute',
    borderRadius: 100,
  },
  noEventsText: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    paddingVertical: 20,
  },
  naPatientsContainer: {
    paddingVertical: 20,
    alignItems: 'center',
  },
  naPatientsText: {
    fontSize: 14,
    color: '#9CA3AF',
  },
  // Name input with د. prefix
  nameInputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    marginBottom: 16,
  },
  doctorPrefix: {
    fontSize: 16,
    fontWeight: '700',
    color: '#2D3748',
    marginLeft: 8,
  },
  nameInput: {
    flex: 1,
    paddingVertical: 14,
    fontSize: 16,
    color: '#2D3748',
  },
  // Treatment Done Modal Styles
  treatmentDoneByMeButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.15)',
    borderRadius: 16,
    padding: 16,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(255, 255, 255, 0.3)',
  },
  treatmentDoneByMeText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#FFFFFF',
  },
  orDivider: {
    flexDirection: 'row',
    alignItems: 'center',
    marginVertical: 20,
  },
  orLine: {
    flex: 1,
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.3)',
  },
  orText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#FFFFFF',
    marginHorizontal: 16,
    opacity: 0.7,
  },
  searchContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    paddingHorizontal: 16,
    paddingVertical: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
    gap: 10,
  },
  searchInput: {
    flex: 1,
    fontSize: 16,
    color: '#FFFFFF',
  },
  doctorsListContainer: {
    maxHeight: 300,
  },
  doctorItem: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.1)',
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: 'rgba(255, 255, 255, 0.2)',
  },
  doctorName: {
    fontSize: 16,
    fontWeight: '500',
    color: '#FFFFFF',
  },
  noDoctorsText: {
    fontSize: 14,
    color: '#9CA3AF',
    textAlign: 'center',
    marginTop: 20,
  },
  // Expanded Dental Section Styles (Permanent Patients)
  dentalTabsContainer: {
    flexDirection: 'row',
    gap: 8,
    marginBottom: 12,
  },
  dentalTab: {
    flex: 1,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 10,
    paddingHorizontal: 8,
    borderRadius: 12,
    backgroundColor: 'transparent',
    marginHorizontal: 3,
  },
  dentalTabActive: {
    backgroundColor: 'rgba(59, 130, 246, 0.15)',
    borderBottomWidth: 3,
    borderBottomColor: '#3B82F6',
  },
  dentalTabText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.4,
  },
  dentalTabTextActive: {
    color: '#3B82F6',
    fontWeight: '800',
  },
  dentalTabContent: {
    maxHeight: 800,
    backgroundColor: 'transparent',
    borderRadius: 14,
    padding: 16,
    shadowColor: 'transparent',
    shadowOffset: { width: 0, height: 0 },
    shadowOpacity: 0,
    shadowRadius: 0,
    elevation: 0,
    borderWidth: 0,
    borderColor: 'transparent',
  },
  dentalTabContentText: {
    fontSize: 13,
    fontWeight: '500',
    color: '#2563EB',
    textAlign: 'center',
    fontStyle: 'italic',
  },
  treatmentContainer: {
    gap: 12,
  },
  dentalSectionContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.6)',
    borderRadius: 12,
    padding: 12,
    borderWidth: 1,
    borderColor: 'rgba(147, 197, 253, 0.3)',
  },
  dentalTreatmentSection: {
    gap: 8,
  },
  dentalTreatmentHeader: {
    marginBottom: 4,
  },
  dentalTreatmentTitle: {
    fontSize: 13,
    fontWeight: '700',
    color: '#1E3A8A',
  },
  teethGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 6,
  },
  toothChip: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1.5,
    minWidth: 50,
    alignItems: 'center',
  },
  toothChipText: {
    fontSize: 12,
    fontWeight: '700',
  },
  // Tooth Edit Modal Styles
  toothModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  toothModalContainer: {
    backgroundColor: '#FFFFFF',
    borderRadius: 20,
    width: '100%',
    maxWidth: 500,
    maxHeight: '80%',
    shadowColor: '#000',
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 10,
  },
  toothModalHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 20,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
  },
  toothModalTitle: {
    fontSize: 24,
    fontWeight: '700',
    color: '#1E3A8A',
  },
  toothModalSubtitle: {
    fontSize: 14,
    color: '#6B7280',
    marginTop: 4,
  },
  toothModalCloseButton: {
    padding: 4,
  },
  toothModalContent: {
    padding: 20,
  },
  toothModalSection: {
    marginBottom: 24,
  },
  toothModalSectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1F2937',
    marginBottom: 12,
  },
  toothModalButtonGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: 10,
  },
  toothModalButton: {
    paddingHorizontal: 16,
    paddingVertical: 10,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: '#E5E7EB',
    backgroundColor: '#F9FAFB',
  },
  toothModalButtonActive: {
    borderColor: '#2563EB',
    backgroundColor: '#EFF6FF',
  },
  toothModalButtonText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#6B7280',
  },
  toothModalButtonTextActive: {
    color: '#2563EB',
  },
  toothModalNoteInput: {
    borderWidth: 1,
    borderColor: '#E5E7EB',
    borderRadius: 10,
    padding: 12,
    fontSize: 14,
    color: '#1F2937',
    backgroundColor: '#F9FAFB',
    minHeight: 100,
    textAlignVertical: 'top',
  },
  toothModalSubmitButton: {
    margin: 20,
    marginTop: 0,
    padding: 16,
    borderRadius: 12,
    backgroundColor: '#E5E7EB',
    alignItems: 'center',
  },
  toothModalSubmitButtonActive: {
    backgroundColor: '#2563EB',
  },
  toothModalSubmitButtonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
  // New Modal Styles from DentalChartScreen
  newModalContainer: {
    flex: 1,
    borderRadius: 24,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    overflow: 'hidden',
    elevation: 8,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 8 },
      shadowOpacity: 0.15,
      shadowRadius: 24,
    } : {}),
  },
  newModalHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 16,
    gap: 12,
  },
  toothNumberBox: {
    backgroundColor: 'rgba(96, 165, 250, 0.2)',
    paddingHorizontal: 14,
    paddingVertical: 10,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    elevation: 2,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    } : {}),
  },
  modalToothNumberText: {
    fontSize: 18,
    fontWeight: 'bold',
    color: '#1E3A8A',
  },
  modalToothNameText: {
    flex: 1,
    fontSize: 16,
    fontWeight: '600',
    color: '#1E3A8A',
  },
  editButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  editButtonActive: {
    backgroundColor: '#60A5FA',
    borderColor: '#3B82F6',
    borderWidth: 2,
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {}),
  },
  headerButtons: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 10,
  },
  closeButton: {
    padding: 10,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    borderRadius: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  headerDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginHorizontal: 16,
  },
  mainSectionsContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    padding: 18,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.08,
      shadowRadius: 8,
    } : {}),
  },
  sectionRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    paddingVertical: 8,
  },
  sectionLabelContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  sectionDivider: {
    height: 1,
    backgroundColor: 'rgba(255, 255, 255, 0.5)',
    marginVertical: 8,
  },
  dropdownInput: {
    width: 170,
    flexDirection: 'row-reverse',
    alignItems: 'center',
    justifyContent: 'space-between',
    backgroundColor: 'rgba(255, 255, 255, 0.75)',
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.5)',
  },
  dropdownInputActive: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.4)',
    elevation: 2,
  },
  dropdownText: {
    flex: 1,
    fontSize: 14,
    fontWeight: '600',
    color: '#334155',
    textAlign: 'center',
  },
  dropdownModalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 5,
  },
  dropdownModalContent: {
    backgroundColor: 'rgba(240, 249, 255, 0.98)',
    borderRadius: 24,
    padding: 22,
    width: '100%',
    maxHeight: '92%',
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.3)',
    elevation: 5,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.2,
      shadowRadius: 12,
    } : {}),
  },
  dropdownModalTitle: {
    fontSize: 20,
    fontWeight: '700',
    color: '#1E3A8A',
    marginBottom: 18,
    textAlign: 'center',
  },
  dropdownModalList: {
    maxHeight: 800,
  },
  dropdownModalOption: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    padding: 16,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.4)',
    marginBottom: 12,
    elevation: 1,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    } : {}),
  },
  optionText: {
    fontSize: 16,
    fontWeight: '600',
    color: '#1E293B',
  },
  radioButton: {
    width: 22,
    height: 22,
    borderRadius: 11,
    borderWidth: 2,
    borderColor: '#94A3B8',
    marginRight: 12,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#FFFFFF',
  },
  radioButtonSelected: {
    borderColor: '#60A5FA',
  },
  radioButtonInner: {
    width: 12,
    height: 12,
    borderRadius: 6,
    backgroundColor: '#60A5FA',
  },
  newNoteContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 12,
    padding: 14,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.35)',
  },
  noteInput: {
    fontSize: 14,
    color: '#1E293B',
    minHeight: 70,
    textAlignVertical: 'top',
    fontWeight: '500',
  },
  submitButtonContainer: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    backgroundColor: 'rgba(248, 250, 252, 0.7)',
    borderTopWidth: 2,
    borderTopColor: 'rgba(203, 213, 225, 0.6)',
  },
  submitButton: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 16,
    borderRadius: 14,
    backgroundColor: 'rgba(226, 232, 240, 0.7)',
    gap: 10,
    borderWidth: 2,
    borderColor: 'rgba(148, 163, 184, 0.5)',
  },
  submitButtonActive: {
    backgroundColor: '#10B981',
    borderColor: '#059669',
    borderWidth: 2,
    elevation: 6,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#10B981',
      shadowOffset: { width: 0, height: 6 },
      shadowOpacity: 0.3,
      shadowRadius: 12,
    } : {}),
  },
  submitButtonText: {
    fontSize: 17,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.5,
  },

  // Tab Buttons Styles
  tabButtons: {
    flexDirection: 'row',
    paddingHorizontal: 12,
    paddingVertical: 12,
    gap: 10,
    backgroundColor: 'rgba(248, 250, 252, 0.9)',
    borderRadius: 16,
    marginHorizontal: 4,
    marginVertical: 4,
    borderWidth: 1,
    borderColor: 'rgba(203, 213, 225, 0.6)',
  },
  tabBtn: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingVertical: 14,
    paddingHorizontal: 6,
    borderRadius: 12,
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    gap: 6,
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.6)',
    elevation: 1,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 1 },
      shadowOpacity: 0.05,
      shadowRadius: 2,
    } : {}),
  },
  tabBtnActive: {
    backgroundColor: '#3B82F6',
    borderWidth: 2,
    borderColor: '#2563EB',
    elevation: 4,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.25,
      shadowRadius: 8,
    } : {}),
  },
  tabBtnText: {
    fontSize: 11,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.3,
  },
  tabBtnTextActive: {
    color: '#FFFFFF',
  },

  // Records Section Styles
  recordsMainContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.9)',
    borderRadius: 16,
    borderWidth: 2,
    borderColor: 'rgba(59, 130, 246, 0.25)',
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 8,
    } : {}),
    padding: 16,
    gap: 12,
  },
  recordsTypeButtons: {
    flexDirection: 'row',
    gap: 10,
    marginBottom: 14,
    justifyContent: 'center',
  },
  recordsTypeBtn: {
    backgroundColor: 'rgba(255, 255, 255, 0.7)',
    paddingVertical: 10,
    paddingHorizontal: 16,
    borderRadius: 8,
    alignItems: 'center',
    borderWidth: 2,
    borderColor: 'rgba(203, 213, 225, 0.6)',
  },
  recordsTypeBtnActive: {
    backgroundColor: '#3B82F6',
    borderColor: '#2563EB',
    borderWidth: 2,
    elevation: 3,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#3B82F6',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.2,
      shadowRadius: 4,
    } : {}),
  },
  recordsTypeBtnText: {
    fontSize: 12,
    fontWeight: '700',
    color: '#64748B',
    letterSpacing: 0.2,
  },
  recordsTypeBtnTextActive: {
    color: '#FFFFFF',
  },
  recordCard: {
    backgroundColor: 'rgba(37, 99, 235, 0.08)',
    borderRadius: 18,
    padding: 20,
    marginBottom: 16,
    borderWidth: 2,
    borderColor: 'rgba(37, 99, 235, 0.35)',
  },
  recordText: {
    fontSize: 14,
    fontWeight: '600',
    color: '#1E293B',
    marginBottom: 6,
  },
  recordSubText: {
    fontSize: 13,
    color: '#64748B',
    fontWeight: '500',
  },

  // Notes Section Styles
  notesSection: {
    gap: 14,
  },
  noteCard: {
    backgroundColor: 'rgba(255, 255, 255, 0.85)',
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
    borderLeftColor: '#3B82F6',
    elevation: 2,
    ...(Platform.OS === 'ios' ? {
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.1,
      shadowRadius: 4,
    } : {}),
  },
  noteHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  noteDoctorName: {
    fontSize: 14,
    fontWeight: '700',
    color: '#1E293B',
  },
  noteTimestamp: {
    fontSize: 11,
    color: '#64748B',
    fontWeight: '500',
  },
  // Convert to Permanent Modal styles
  input: {
    backgroundColor: '#F9FAFB',
    borderRadius: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    paddingHorizontal: 16,
    paddingVertical: 14,
    fontSize: 16,
    color: '#2D3748',
    marginBottom: 8,
  },
  button: {
    backgroundColor: '#3B82F6',
    borderRadius: 12,
    paddingVertical: 14,
    alignItems: 'center' as const,
    justifyContent: 'center' as const,
  },
  buttonText: {
    fontSize: 16,
    fontWeight: '700',
    color: '#FFFFFF',
  },
});
